  const editions = [
  {
    id: "1",
    slug: "laudano-para-el-corazon-negro",
    image: "/1.webp",
    title: "Láudano para el corazón negro",
    author: "María Magdalena",
    authorImage: "/author-1.png",
    authorBio: `María Magdalena (1984, Buenos Aires). Poeta y escritora. Psicoanalista. Editora en Las Furias. Publicó los libros de poesía <i>Spleen</i> (2013, Letra Viva), <i>Los nombres del padre</i> (2016, Buenos Aires Poetry), la plaquette artesanal <i>La pequeña muerte</i> (2015), <i>Continente negro</i> (2018, Alción; 2021, el diván negro –México–), <i>Un invierno sin Emma</i> (2022, Vagantes Fabulae), y los ensayos <i>La perfecta desnudez. Conversaciones desde Alejandra Pizarnik</i> (2018, Letra Viva) en co-autoría con Javier Galarza y Leonardo Leibson, <i>Diario de la errancia. Elogio del viaje</i> (2020, La Docta Ignorancia) y <i>No hay milagro más cruel que este. Sylvia Plath: amar, maternar, escribir</i> (2022, Las Furias).`,
    review: `Hay escrituras que respiran entre las grietas producidas por su carácter disruptivo. María Magdalena lo demuestra en cada libro, desacomoda las formas hasta que entonen un canto singular. Ahí encuentra su descanso. En <i>Láudano para el corazón negro</i> nos entrega un extenso poema fragmentado, acuchillado: <i>¿Y si fuiste herida en el río?</i> // <i>¿Y si dijeron las palabras</i> / <i>cuchillos</i> / <i>las palabras filo</i> / <i>una tarde de verano</i> / <i>en el río?</i> /. Cada escena del crimen nos conduce a otra en una especie de conjuro que retorna y punza, un conjuro que busca un antídoto donde ponernos a salvo en este escenario tan lírico como cruel.`,
    reviewName: "Enzo Amarillo",
    price: "15000",
    link: "https://pency.app/eldesenfreno/laudano-para-el-corazon-negro-maria-magdalena_64120aa389817800087b5df8",
  },
  {
    id: "2",
    slug: "haran-una-pelicula-con-mi-entierro",
    image: "/2.webp",
    title: "Harán una película con mi entierro",
    author: "María Malusardi",
    authorImage: "/author-2.png",
    authorBio: `María Malusardi nació en Buenos Aires, Argentina, en 1966. Escritora, periodista y docente. Obra: <i>Una madre es un piano triste</i> (Las Furias Editora, 2021), <i>Artista del hambre</i> (Ediciones en Danza, 2019), <i>El descenso de jacqueline du pré y otros poemas</i> (Ediciones en Danza, 2018), <i>El desvío y el daño</i> (Cadáver exquisito, 2023 edición realizada en Ecuador y editorial Buenos Aires Poetry, 2017), <i>El sastre</i> (Ediciones en Danza, 2015), <i>Artista del trapecio</i> (Alción, 2014), <i>La música</i> (El suri porfiado, 2013), <i>El orfanato</i> (Alción, 2010), <i>Trilogía de la tristeza</i> (Alción, 2009), <i>Museo de postales</i> (El suri porfiado, 2008), <i>Diálogo con pescadores</i> (Alción, 2007), <i>Variaciones en la niebla</i> (Alción, 2005), <i>La carta de vermeer</i> (Alción, 2002) y <i>El accidente</i> (Mascaró, 2001).<br/>Obtuvo por <i>El sastre</i>, la Mención especial del Premio de Literatura Casa de las Américas 2015, de Cuba. Y por <i>Artista del hambre</i> el Segundo Premio Municipal de Poesía 2018-2019. Y <i>Trilogía de la tristeza</i> resultó finalista del Concurso Olga Orozco 2009 que organizó la Universidad de San Martín, con un jurado integrado por Antonio Gamoneda, Gonzalo Rojas, Juan Gelman y Jorge Boccanera; además fue traducido al francés y editado en 2013 como <i>Trilogie de la tristesse</i> (Zinnia Editions), tanto en papel como en formato e-book.<br/>Recibió en 2018 la beca del Fondo Nacional de las Artes para escribir <i>Asamblea permanente. Diálogos para una hermenéutica</i>, un ensayo sobre la obra y vida del poeta argentino Alberto Szpunberg.<br/>Estuvo a cargo de la edición y estudio preliminar de la poesía de Raúl Gustavo Aguirre en el volumen <i>Obra poética</i> (Ediciones Del dock, 2015) y del ensayo <i>Las poéticas del siglo XX</i> (Audisea, 2016).<br/><i>Nadie sabe qué hacer con los poetas</i>, próximamente editado por Llantén, reúne sus escritos sobre poesía, publicados e inéditos.`,
    review: `El lenguaje permite lo imposible. El yo asiste a su funeral y sostiene la voz. En la ceremonia, los verbos sacan las mortajas al sol y cantan. El futuro es puro lenguaje: está hecho de acciones que se lanzan hacia adelante como serpentinas de deseo, furia o dolor. La vida después es un estribillo que repiquetea en los días por venir. En el entierro de la obra, el poema labra el testamento, y también ríe y baila sobre su tumba. Es imposible no hacerse la película. La sábana del lecho es la pantalla en la que pasará la vida: ojos, roces, harapos, huellas, hijos. Un campanario y los zapatos. ¿Qué harán con la desnudez y la soledad? ¿Adónde irán las esquinas y las lápidas? Con voz acicalada de humor y finitud, María Malusardi nos acerca a los efectos secundarios de la muerte y ofrece —para quienes no sabemos morir ni rezar— un conjunto de poemas sobre esa loca fantasía.`,
    reviewName: "Gabriela Franco",
    price: "15000",
    link: "https://pency.app/eldesenfreno/haran-una-pelicula-con-mi-entierro-maria-malusardi_646e4b7356c90a0008dcbdab",
  },
  {
    id: "3",
    slug: "padre-totem-oscuros-umbrales-de-revelacion",
    image: "/3.webp",
    title: "Padre Tótem - Oscuros umbrales de revelación",
    author: "Diego Roel",
    authorImage: "/author-3.png",
    authorBio: `Diego Roel nació en Temperley, Provincia de Buenos Aires, en 1980. Publicó <i>Padre Tótem/ Oscuros umbrales de revelación</i> (Libros de Tierra Firme, 2004; El Mono Armado, 2012), <i>Diario del insomnio</i> (Libros de Tierra Firme, 2005; detodoslosmares, 2013), <i>Cuaderno del desierto</i> (Libros de Tierra Firme, 2007), <i>Las variaciones del mundo</i> (El Mono Armado, 2010; detodoslosmares, 2014), <i>Los Jardines del Aire</i> (El Mono Armado, 2012), <i>Dice Jonás</i> (El Mono Armado, 2015), <i>Vía Lucis</i> (Ediciones del Dock, 2015), <i>Kyrios</i> (detodoslosmares, 2016; Sirga, 2016), <i>Las intemperies del mar</i> (detodoslosmares, 2017), <i>Shibólet</i> (Griselda García editora, 2018), <i>Kadosh</i> (detodoslosmares, 2019), <i>El infierno es una bestia callada y triste</i> (detodoslosmares, 2020) y <i>Andréi Rubliov</i> (Premio Alegría 2020 del Ayuntamiento de Santander, Ediciones Rialp, colección Adonáis, Madrid, 2020).<br/>Un jurado presidido por Victor García de la Concha e integrado por los poetas y narradores Gioconda Belli, Antonio Colinas, Aurora Egido, María Negroni, Juan Antonio González Iglesias, Carme Riera, Jaime Siles, Luis Antonio de Villena y Reiniel Pérez Ventura, le concedió el <i>Premio Internacional Loewe de Poesía 2023</i> por su libro <i>Los cuadernos perdidos de Robert Walser</i>. El libro fue editado por la editorial Visor (España) en marzo de 2024.<br/>Poemas suyos fueron incluidos en diversas antologías de Argentina, entre ellas: <i>Desorbitados. Poetas novísimos del sur de la Argentina</i> (Fondo Nacional de las Artes, 2009); <i>Si Hamlet duda le daremos muerte</i> (Libros de la Talita dorada, 2010); <i>Antología Federal de Poesía. Provincia de Buenos Aires</i> (CFI, 2019); <i>Poesía, Varios Autores, La Plata</i> (La Comuna Ediciones, 2019); <i>Roberto Juarroz baja en Temperley. Un mapa posible de la poesía en el conurbano sur</i> (Leviatán, 2021). Ha colaborado en numerosas publicaciones tanto en Argentina como en el exterior. Actualmente dicta talleres de escritura creativa. Estudió Historia de las Artes visuales en la Universidad Nacional de La Plata (U.N.L.P.). Reside en la ciudad de Posadas.`,
    review: `El desamparo existencial, la orfandad cósmica, el duelo del alma por el cuerpo, son el punto de partida de esta lírica orientada hacia la búsqueda del padre totémico, el padre simbólico, el protector absoluto. Padre que es, a la vez, hijo de sí mismo y cuya <i>boca de mil lenguas de oro</i> arroja al mundo <i>en una cuna negra</i>, en <i>un ataúd de repleto de blancas mariposas</i>. Este padre-hijo, este <i>animal cosido al silencio</i>, carece de Yo, de nombre propio, o para decirlo en términos lacanianos, del <i>corazón brillante del sujeto</i>. En este punto, la lírica de Diego Roel se convierte -sustancialmente- en una épica, que si lo propio del sujeto es su falta del nombre, si como se ha dicho <i>el inconsciente es el olvido del propio nombre</i>, todos los caminos están cerrados y sólo queda el trazo, la vaga huella de una relación borrada por el mismo acto de la nominación. Como dice Roel: <i>sólo queda sumergirse / resignarse al acaso como al tiempo / después de este río atravesaremos otro río y otro río / porque no hay desembocadura ni salida / no hay delante del camino no hay dónde / y sumergidos naufragamos / arrastrados por los efluvios de los días / sin un Padre una Madre sin un Tótem</i>. Dicho de otro modo: no hay sino naufragio en el <i>mare de l'essere</i> de que habla Dante, y ése es el único nombre que podemos ostentar: la pérdida de sí mismo, lo <i>sin techo</i>, <i>sin guarida</i>, puro vacío que sólo puede llenar otro mar, el de la poesía.`,
    reviewName: "Horacio Castillo",
    price: "15000",
    link: "https://pency.app/eldesenfreno/diego-roel-padre-totem-or-oscuros-umbrales-de-revelacion_6772b5ba1d2b6500030e1cb7",
  },
  {
    id: "4",
    slug: "el-veneno-del-manto",
    image: "/4.webp",
    title: "El veneno del manto",
    author: "Enzo Amarillo",
    authorImage: "/author-4.png",
    authorBio: `Enzo Amarillo nació en Concepción del Uruguay, Entre Ríos. Vive actualmente en la Ciudad de Buenos Aires. Publicó los libros <i>Una fiesta sepultada</i> (Modesto Rimba, 2016), <i>Los descampados</i> (Buenos Aires Poetry, 2019), <i>El veneno del manto</i> (El desenfreno, 2024).`,
    review: `No es la noche abierta que despliega el universo y nos arropa, sino un sótano sin estrellas donde habitan el sopor y la violencia como un silencio de muerte. Ni balas ni látigos ni cuchillos. Sólo la soledad de un cuerpo sórdido, desmembrado y deseoso de ser deseado, amado, acunado sin fin. Así el clima que nos arroja en la cara <i>El veneno del manto</i> de Enzo Amarillo.<br/>Una voz narra desanimándose, montada sobre un lenguaje fértil y movedizo. El tono de cada uno de estos poemas en prosa mantiene la potencia y la sensualidad brutal que despide el epígrafe de Susana Villalba, tan bien elegido, tan atinado para restaurar la confusión de una trama que, de tan espesa, ahoga. No porque haya maraña, sino porque duele tiernamente tan grosero abandono, tan humillante condición sumida en la belleza del más armonioso devenir poético: <i>Es divina esta peste. Este basural codiciado.</i><br/>Lo mejor: el contraste entre el lirismo y la desgarradura. <i>No importa si de este viaje no regresa</i>. Hay que <i>acostarse sobre el peligro</i>. Y dejarse amansar por la dulzura del infierno. O armar <i>otro paisaje donde existir fuera del duelo</i>.`,
    reviewName: "María Malusardi",
    price: "15000",
    link: "https://pency.app/eldesenfreno/enzo-amarillo-el-veneno-del-manto_6772b4e2b23ba40003509c1d",
  },
  {
    id: "5",
    slug: "maquina-para-hablar-con-los-muertos",
    image: "/5.webp",
    title: "Máquina para hablar con los muertos",
    author: "Carmen García Palma",
    authorImage: "/author-5.png",
    authorBio: `Carmen García Palma nació una mañana de marzo a fines de la década del setenta. Creció entre pájaros y animales. Ha publicado los libros de poesía <i>La insistencia</i> (Libros de la Elipse, 2004), <i>Gotas sobre loza fría</i> (Cuarto Propio, 2011) y <i>Máquina para hablar con los muertos</i> (Ediciones Bastante, 2016). Su primera incursión narrativa fue la novela <i>Las Oscurecidas</i> (Planeta, 2018). El 2021 publicó el libro de cuentos <i>María y el fuego</i> (Neón Ediciones, 2021), que recibió la Mención Especial del Jurado de los Premios Literarios del Ministerio de las Culturas. Su libro de poemas <i>El lugar donde nacimos por última vez</i> (Pez Espiral, 2023), fue finalista del XXXV Premio Internacional de Poesía de Fundación Loewe con el título <i>Ya nadie habita este pueblo azul</i>. Es máster en creación literaria de la Universidad Pompeu Fabra. Sus poemas han sido incluidos en diversas publicaciones y antologías. Es fundadora y directora de Fundación Plagio. Tiene una fascinación por las islas. Le gustaría vivir en la selva y hablar el idioma de los pájaros.`,
    review: `En este libro hay una mujer rodeada de sombras y voces asediantes, quizás se trata del primer vertebrado en pisar tierra firme. Vive en una isla que es un templo donde todo muta y murmura, donde el sueño es un portal. Pero debe partir.<br/>El viaje la lleva a una ciudad que arde, donde las estaciones pasan como las voces de los hombres y las palabras se vuelven fríos monumentos sin razón.<br/>Tiene cien años y desde niña sabe que el mayor placer es desaparecer. La ciudad hace posible ese acto de magia, pero trae consigo el paso de la inocencia al conocimiento. Desde el muelle puede verse la isla dormida, la promesa de los amaneceres multiplicados hasta el infinito.<br/>Carmen García Palma escribió <i>Máquina para hablar con los muertos</i> entregándose sin reservas a la palabra, dejando que los sueños sean poemas y los cuentos sean sueños.`,
    reviewName: "Rodrigo Olavarría",
    price: "15000",
    link: "https://pency.app/eldesenfreno/carmen-garcia-palma-maquina-para-hablar-con-los-muertos-precio-preventa_67c342edf8123400032c54d8",
  },
  {
    id: "6",
    slug: "mordida-por-las-flores",
    image: "/6.jpg",
    title: "Mordida por las flores",
    author: "Yanina Audisio",
    authorImage: "/author-6.JPG",
    authorBio: `Yanina Audisio nació en 1983 en Río Cuarto, Córdoba, Argentina. Reside en Buenos Aires.<br/>Ha publicado los poemarios <i>La noche en los perros</i>, <i>La boca y su testigo</i> (Primer premio 7mo Concurso de Cuento y Poesía Adolfo Bioy Casares), <i>Piedras, papeles, tijeras</i>, <i>Bajo poncho</i>, <i>Cielo sobre el charco</i>, <i>Paragüería y otros poemas</i> (infantil), <i>Sol por un rato</i> (Mención honorífica Convocatoria 2020 Nueva York Poetry Press), Nombradero y <i>Hacer el lobo</i> (XXV Premio Latinoamericano de Poesía Ciro Mendía).<br/>Ha sido galardonada con el Accésit Juan Ramón Jiménez - Zenobia Camprubí, destinado a poetas que residen fuera de España, del VI Premio de Poesía Viva, por la interpretación performática de poemas de su autoría.<br/>En cuanto a su obra narrativa, ha editado el libro de cuentos <i>Rancho aparte</i> y obtuvo la Mención Especial del Jurado de Letras del Concurso Bienal Premio Federal 2019 con su nouvelle <i>El filo para arriba</i>. Su cuento <i>Dionisio</i> recibió una mención en el Concurso XXII Premio Iberoamericano de Cuento Julio Cortázar, auspiciado por Casa de las Américas, Cuba.<br/>Tradujo <i>Fantasmas de lo sublime. Poesía en lengua inglesa en torno a la finitud y la trascendencia</i> (en cotraducción junto a Federico Sironi) y <i>Pájaros de oscuras vocales. Poesía temprana de Dylan Thomas</i>.<br/><i>Mordida por las flores</i> recibió la mención especial del Premio Municipal de Literatura <i>Luis José de Tejeda</i> 2024, género Poesía. El jurado, conformado por Claudia Masin, Leandro Manuel Calle y Juan Pablo Abraham, refiere respecto de la obra: "El texto construye una prosa poética de tono confesional, en la que el cuerpo funciona como territorio del dolor. A través de imágenes precisas —la migraña, el armadillo, las flores que muerden, entre otras—, el yo lírico traza una genealogía íntima del sufrimiento, donde lo corporal y lo simbólico se confunden. Fragmento a fragmento, el libro elabora una poética del dolor que conmueve sin artificios, y se afirma en una escritura que se atreve a nombrar lo que duele, sin renunciar a la belleza."`,
    review: `<i>Mordida por las flores</i> -¡qué título tan baudeleriano!- nos propone una temporada en el infierno. Como una Rimbaud desenfocada, Yanina Audisio arroja imágenes artaudianas tan perturbadoras como excitantes. La sorpresa es permanente; el sobresalto, estético. Estas tres ineludibles herencias quedarán desfiguradas en la pluma originalísima de esta poeta argentina que despliega una lírica del dolor corporal y del desasosiego animada por un imaginario simbolista que, párrafo a párrafo, nos deja en estado de compasiva admiración. Es una escritura que nos retiene, en contra de todo intento de fuga, obligándonos al merodeo: paladear la imagen, recibir su belleza y su vértigo, experimentar, de verdad, el don poético como una incómoda celebración en la zona malograda de un cuerpo capaz de ahogarse en la palabra en pos de su resarcimiento.`,
    reviewName: "María Malusardi",
    price: "15000",
    link: "",
  },
  {
    id: "7",
    slug: "desparramo-va",
    image: "/7.jpeg",
    title: "DESPARRAMO V/A",
    author: "Varios Artistas",
    authorImage: null,
    authorBio: null,
    review: `Si una fuerza se expande es porque hay vértices que comulgan con ella, se estiran hasta el encuentro para que el acontecimiento suceda. Hay un orden cansado de sí mismo, un temblor anunciando la mutación de su forma.

"Desparramo V/A" busca esa comunión entre lo sonoro y la palabra para que, ahí donde uno descansa, el otro sostenga el fuego.


Idea y compilación: Enzo Amarillo
Master: Oriana Tosi
Artwork: Plantasia
`,
    reviewName: "El Desenfreno Ediciones",
    price: "8000",
    link: "",
    tracklist: [
      { number: 1, artist: "Catriel Nievas", title: "An(geologist) II", duration: "04:35" },
      { number: 2, artist: "María Magdalena", title: "Láudano para el corazón negro", duration: "01:17" },
      { number: 3, artist: "Lusiaen", title: "Dspota", duration: "02:40" },
      { number: 4, artist: "María Malusardi", title: "Harán una película con mi entierro", duration: "01:22" },
      { number: 5, artist: "Lila", title: "Anhelo", duration: "04:44" },
      { number: 6, artist: "Rvrls", title: "Mates con iván", duration: "04:20" },
      { number: 7, artist: "Diego Roel", title: "Padre tótem | Oscuros umbrales de revelación", duration: "01:13" },
      { number: 8, artist: "Sáccea", title: "Refleja el río", duration: "03:20" },
      { number: 9, artist: "Enzo Amarillo", title: "El veneno del manto", duration: "01:09" },
      { number: 10, artist: "UnknownSoul", title: "Anábasis", duration: "03:51" },
    ],
  },
];

export default editions;
