import { Inter } from 'next/font/google'
import './globals.css'
import localFont from 'next/font/local';

const inter = Inter({ subsets: ['latin'] })
const aggie = localFont({
  src: [
    {
      path: '../public/fonts/Aggie-Regular.otf',
      weight: '400',
    }
  ],
  variable: '--font-aggie'
});


export const metadata = {
  stylesheet: 'https://use.typekit.net/maa8yuy.css',
  title: 'El Desenfreno Ediciones',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={aggie.className}>{children}</body>
    </html>
  )
}
